# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lyx/projects/dss

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lyx/projects/dss

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lyx/projects/dss/CMakeFiles /home/lyx/projects/dss/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lyx/projects/dss/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/lyx/projects/dss/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dtplayer-examples

# Build rule for target.
dtplayer-examples: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dtplayer-examples
.PHONY : dtplayer-examples

# fast build rule for target.
dtplayer-examples/fast:
	$(MAKE) -f CMakeFiles/dtplayer-examples.dir/build.make CMakeFiles/dtplayer-examples.dir/build
.PHONY : dtplayer-examples/fast

#=============================================================================
# Target rules for targets named cargo-clean_quiche-server

# Build rule for target.
cargo-clean_quiche-server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cargo-clean_quiche-server
.PHONY : cargo-clean_quiche-server

# fast build rule for target.
cargo-clean_quiche-server/fast:
	$(MAKE) -f CMakeFiles/cargo-clean_quiche-server.dir/build.make CMakeFiles/cargo-clean_quiche-server.dir/build
.PHONY : cargo-clean_quiche-server/fast

#=============================================================================
# Target rules for targets named _cargo-build_quiche

# Build rule for target.
_cargo-build_quiche: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _cargo-build_quiche
.PHONY : _cargo-build_quiche

# fast build rule for target.
_cargo-build_quiche/fast:
	$(MAKE) -f CMakeFiles/_cargo-build_quiche.dir/build.make CMakeFiles/_cargo-build_quiche.dir/build
.PHONY : _cargo-build_quiche/fast

#=============================================================================
# Target rules for targets named cargo-prebuild_quiche-server

# Build rule for target.
cargo-prebuild_quiche-server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cargo-prebuild_quiche-server
.PHONY : cargo-prebuild_quiche-server

# fast build rule for target.
cargo-prebuild_quiche-server/fast:
	$(MAKE) -f CMakeFiles/cargo-prebuild_quiche-server.dir/build.make CMakeFiles/cargo-prebuild_quiche-server.dir/build
.PHONY : cargo-prebuild_quiche-server/fast

#=============================================================================
# Target rules for targets named cargo-prebuild_quiche

# Build rule for target.
cargo-prebuild_quiche: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cargo-prebuild_quiche
.PHONY : cargo-prebuild_quiche

# fast build rule for target.
cargo-prebuild_quiche/fast:
	$(MAKE) -f CMakeFiles/cargo-prebuild_quiche.dir/build.make CMakeFiles/cargo-prebuild_quiche.dir/build
.PHONY : cargo-prebuild_quiche/fast

#=============================================================================
# Target rules for targets named _cargo-build_quiche-client

# Build rule for target.
_cargo-build_quiche-client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _cargo-build_quiche-client
.PHONY : _cargo-build_quiche-client

# fast build rule for target.
_cargo-build_quiche-client/fast:
	$(MAKE) -f CMakeFiles/_cargo-build_quiche-client.dir/build.make CMakeFiles/_cargo-build_quiche-client.dir/build
.PHONY : _cargo-build_quiche-client/fast

#=============================================================================
# Target rules for targets named cargo-build_quiche-server

# Build rule for target.
cargo-build_quiche-server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cargo-build_quiche-server
.PHONY : cargo-build_quiche-server

# fast build rule for target.
cargo-build_quiche-server/fast:
	$(MAKE) -f CMakeFiles/cargo-build_quiche-server.dir/build.make CMakeFiles/cargo-build_quiche-server.dir/build
.PHONY : cargo-build_quiche-server/fast

#=============================================================================
# Target rules for targets named cargo-build_quiche

# Build rule for target.
cargo-build_quiche: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cargo-build_quiche
.PHONY : cargo-build_quiche

# fast build rule for target.
cargo-build_quiche/fast:
	$(MAKE) -f CMakeFiles/cargo-build_quiche.dir/build.make CMakeFiles/cargo-build_quiche.dir/build
.PHONY : cargo-build_quiche/fast

#=============================================================================
# Target rules for targets named _cargo-build_quiche-server

# Build rule for target.
_cargo-build_quiche-server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _cargo-build_quiche-server
.PHONY : _cargo-build_quiche-server

# fast build rule for target.
_cargo-build_quiche-server/fast:
	$(MAKE) -f CMakeFiles/_cargo-build_quiche-server.dir/build.make CMakeFiles/_cargo-build_quiche-server.dir/build
.PHONY : _cargo-build_quiche-server/fast

#=============================================================================
# Target rules for targets named cargo-prebuild

# Build rule for target.
cargo-prebuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cargo-prebuild
.PHONY : cargo-prebuild

# fast build rule for target.
cargo-prebuild/fast:
	$(MAKE) -f CMakeFiles/cargo-prebuild.dir/build.make CMakeFiles/cargo-prebuild.dir/build
.PHONY : cargo-prebuild/fast

#=============================================================================
# Target rules for targets named dtplayer-core

# Build rule for target.
dtplayer-core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dtplayer-core
.PHONY : dtplayer-core

# fast build rule for target.
dtplayer-core/fast:
	$(MAKE) -f CMakeFiles/dtplayer-core.dir/build.make CMakeFiles/dtplayer-core.dir/build
.PHONY : dtplayer-core/fast

#=============================================================================
# Target rules for targets named cargo-clean_quiche

# Build rule for target.
cargo-clean_quiche: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cargo-clean_quiche
.PHONY : cargo-clean_quiche

# fast build rule for target.
cargo-clean_quiche/fast:
	$(MAKE) -f CMakeFiles/cargo-clean_quiche.dir/build.make CMakeFiles/cargo-clean_quiche.dir/build
.PHONY : cargo-clean_quiche/fast

#=============================================================================
# Target rules for targets named cargo-build_quiche-client

# Build rule for target.
cargo-build_quiche-client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cargo-build_quiche-client
.PHONY : cargo-build_quiche-client

# fast build rule for target.
cargo-build_quiche-client/fast:
	$(MAKE) -f CMakeFiles/cargo-build_quiche-client.dir/build.make CMakeFiles/cargo-build_quiche-client.dir/build
.PHONY : cargo-build_quiche-client/fast

#=============================================================================
# Target rules for targets named cargo-clean

# Build rule for target.
cargo-clean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cargo-clean
.PHONY : cargo-clean

# fast build rule for target.
cargo-clean/fast:
	$(MAKE) -f CMakeFiles/cargo-clean.dir/build.make CMakeFiles/cargo-clean.dir/build
.PHONY : cargo-clean/fast

#=============================================================================
# Target rules for targets named cargo-prebuild_quiche-client

# Build rule for target.
cargo-prebuild_quiche-client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cargo-prebuild_quiche-client
.PHONY : cargo-prebuild_quiche-client

# fast build rule for target.
cargo-prebuild_quiche-client/fast:
	$(MAKE) -f CMakeFiles/cargo-prebuild_quiche-client.dir/build.make CMakeFiles/cargo-prebuild_quiche-client.dir/build
.PHONY : cargo-prebuild_quiche-client/fast

#=============================================================================
# Target rules for targets named cargo-clean_quiche-client

# Build rule for target.
cargo-clean_quiche-client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cargo-clean_quiche-client
.PHONY : cargo-clean_quiche-client

# fast build rule for target.
cargo-clean_quiche-client/fast:
	$(MAKE) -f CMakeFiles/cargo-clean_quiche-client.dir/build.make CMakeFiles/cargo-clean_quiche-client.dir/build
.PHONY : cargo-clean_quiche-client/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/NightlyTest.dir/build.make _deps/corrosion-build/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/ContinuousConfigure.dir/build.make _deps/corrosion-build/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/ContinuousBuild.dir/build.make _deps/corrosion-build/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/NightlyConfigure.dir/build.make _deps/corrosion-build/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/NightlyMemoryCheck.dir/build.make _deps/corrosion-build/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/ExperimentalTest.dir/build.make _deps/corrosion-build/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/ContinuousUpdate.dir/build.make _deps/corrosion-build/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/NightlyUpdate.dir/build.make _deps/corrosion-build/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/ExperimentalMemCheck.dir/build.make _deps/corrosion-build/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/ExperimentalSubmit.dir/build.make _deps/corrosion-build/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/Experimental.dir/build.make _deps/corrosion-build/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/ContinuousCoverage.dir/build.make _deps/corrosion-build/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/ExperimentalConfigure.dir/build.make _deps/corrosion-build/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/Continuous.dir/build.make _deps/corrosion-build/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/Nightly.dir/build.make _deps/corrosion-build/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/NightlySubmit.dir/build.make _deps/corrosion-build/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/NightlyStart.dir/build.make _deps/corrosion-build/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/ExperimentalCoverage.dir/build.make _deps/corrosion-build/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/NightlyCoverage.dir/build.make _deps/corrosion-build/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/ExperimentalStart.dir/build.make _deps/corrosion-build/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/NightlyBuild.dir/build.make _deps/corrosion-build/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/ExperimentalBuild.dir/build.make _deps/corrosion-build/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/ExperimentalUpdate.dir/build.make _deps/corrosion-build/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/ContinuousStart.dir/build.make _deps/corrosion-build/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/ContinuousMemCheck.dir/build.make _deps/corrosion-build/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/ContinuousTest.dir/build.make _deps/corrosion-build/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/ContinuousSubmit.dir/build.make _deps/corrosion-build/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f _deps/corrosion-build/CMakeFiles/NightlyMemCheck.dir/build.make _deps/corrosion-build/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

examples/client.o: examples/client.c.o

.PHONY : examples/client.o

# target to build an object file
examples/client.c.o:
	$(MAKE) -f CMakeFiles/dtplayer-examples.dir/build.make CMakeFiles/dtplayer-examples.dir/examples/client.c.o
.PHONY : examples/client.c.o

examples/client.i: examples/client.c.i

.PHONY : examples/client.i

# target to preprocess a source file
examples/client.c.i:
	$(MAKE) -f CMakeFiles/dtplayer-examples.dir/build.make CMakeFiles/dtplayer-examples.dir/examples/client.c.i
.PHONY : examples/client.c.i

examples/client.s: examples/client.c.s

.PHONY : examples/client.s

# target to generate assembly for a file
examples/client.c.s:
	$(MAKE) -f CMakeFiles/dtplayer-examples.dir/build.make CMakeFiles/dtplayer-examples.dir/examples/client.c.s
.PHONY : examples/client.c.s

examples/server.o: examples/server.c.o

.PHONY : examples/server.o

# target to build an object file
examples/server.c.o:
	$(MAKE) -f CMakeFiles/dtplayer-examples.dir/build.make CMakeFiles/dtplayer-examples.dir/examples/server.c.o
.PHONY : examples/server.c.o

examples/server.i: examples/server.c.i

.PHONY : examples/server.i

# target to preprocess a source file
examples/server.c.i:
	$(MAKE) -f CMakeFiles/dtplayer-examples.dir/build.make CMakeFiles/dtplayer-examples.dir/examples/server.c.i
.PHONY : examples/server.c.i

examples/server.s: examples/server.c.s

.PHONY : examples/server.s

# target to generate assembly for a file
examples/server.c.s:
	$(MAKE) -f CMakeFiles/dtplayer-examples.dir/build.make CMakeFiles/dtplayer-examples.dir/examples/server.c.s
.PHONY : examples/server.c.s

lib/dtp_assemb.o: lib/dtp_assemb.c.o

.PHONY : lib/dtp_assemb.o

# target to build an object file
lib/dtp_assemb.c.o:
	$(MAKE) -f CMakeFiles/dtplayer-core.dir/build.make CMakeFiles/dtplayer-core.dir/lib/dtp_assemb.c.o
.PHONY : lib/dtp_assemb.c.o

lib/dtp_assemb.i: lib/dtp_assemb.c.i

.PHONY : lib/dtp_assemb.i

# target to preprocess a source file
lib/dtp_assemb.c.i:
	$(MAKE) -f CMakeFiles/dtplayer-core.dir/build.make CMakeFiles/dtplayer-core.dir/lib/dtp_assemb.c.i
.PHONY : lib/dtp_assemb.c.i

lib/dtp_assemb.s: lib/dtp_assemb.c.s

.PHONY : lib/dtp_assemb.s

# target to generate assembly for a file
lib/dtp_assemb.c.s:
	$(MAKE) -f CMakeFiles/dtplayer-core.dir/build.make CMakeFiles/dtplayer-core.dir/lib/dtp_assemb.c.s
.PHONY : lib/dtp_assemb.c.s

lib/dtp_scheduler.o: lib/dtp_scheduler.c.o

.PHONY : lib/dtp_scheduler.o

# target to build an object file
lib/dtp_scheduler.c.o:
	$(MAKE) -f CMakeFiles/dtplayer-core.dir/build.make CMakeFiles/dtplayer-core.dir/lib/dtp_scheduler.c.o
.PHONY : lib/dtp_scheduler.c.o

lib/dtp_scheduler.i: lib/dtp_scheduler.c.i

.PHONY : lib/dtp_scheduler.i

# target to preprocess a source file
lib/dtp_scheduler.c.i:
	$(MAKE) -f CMakeFiles/dtplayer-core.dir/build.make CMakeFiles/dtplayer-core.dir/lib/dtp_scheduler.c.i
.PHONY : lib/dtp_scheduler.c.i

lib/dtp_scheduler.s: lib/dtp_scheduler.c.s

.PHONY : lib/dtp_scheduler.s

# target to generate assembly for a file
lib/dtp_scheduler.c.s:
	$(MAKE) -f CMakeFiles/dtplayer-core.dir/build.make CMakeFiles/dtplayer-core.dir/lib/dtp_scheduler.c.s
.PHONY : lib/dtp_scheduler.c.s

lib/dtp_tc.o: lib/dtp_tc.c.o

.PHONY : lib/dtp_tc.o

# target to build an object file
lib/dtp_tc.c.o:
	$(MAKE) -f CMakeFiles/dtplayer-core.dir/build.make CMakeFiles/dtplayer-core.dir/lib/dtp_tc.c.o
.PHONY : lib/dtp_tc.c.o

lib/dtp_tc.i: lib/dtp_tc.c.i

.PHONY : lib/dtp_tc.i

# target to preprocess a source file
lib/dtp_tc.c.i:
	$(MAKE) -f CMakeFiles/dtplayer-core.dir/build.make CMakeFiles/dtplayer-core.dir/lib/dtp_tc.c.i
.PHONY : lib/dtp_tc.c.i

lib/dtp_tc.s: lib/dtp_tc.c.s

.PHONY : lib/dtp_tc.s

# target to generate assembly for a file
lib/dtp_tc.c.s:
	$(MAKE) -f CMakeFiles/dtplayer-core.dir/build.make CMakeFiles/dtplayer-core.dir/lib/dtp_tc.c.s
.PHONY : lib/dtp_tc.c.s

lib/dtplayer.o: lib/dtplayer.c.o

.PHONY : lib/dtplayer.o

# target to build an object file
lib/dtplayer.c.o:
	$(MAKE) -f CMakeFiles/dtplayer-core.dir/build.make CMakeFiles/dtplayer-core.dir/lib/dtplayer.c.o
.PHONY : lib/dtplayer.c.o

lib/dtplayer.i: lib/dtplayer.c.i

.PHONY : lib/dtplayer.i

# target to preprocess a source file
lib/dtplayer.c.i:
	$(MAKE) -f CMakeFiles/dtplayer-core.dir/build.make CMakeFiles/dtplayer-core.dir/lib/dtplayer.c.i
.PHONY : lib/dtplayer.c.i

lib/dtplayer.s: lib/dtplayer.c.s

.PHONY : lib/dtplayer.s

# target to generate assembly for a file
lib/dtplayer.c.s:
	$(MAKE) -f CMakeFiles/dtplayer-core.dir/build.make CMakeFiles/dtplayer-core.dir/lib/dtplayer.c.s
.PHONY : lib/dtplayer.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... dtplayer-examples"
	@echo "... cargo-clean_quiche-server"
	@echo "... _cargo-build_quiche"
	@echo "... cargo-prebuild_quiche-server"
	@echo "... cargo-prebuild_quiche"
	@echo "... _cargo-build_quiche-client"
	@echo "... cargo-build_quiche-server"
	@echo "... cargo-build_quiche"
	@echo "... _cargo-build_quiche-server"
	@echo "... cargo-prebuild"
	@echo "... dtplayer-core"
	@echo "... cargo-clean_quiche"
	@echo "... cargo-build_quiche-client"
	@echo "... cargo-clean"
	@echo "... cargo-prebuild_quiche-client"
	@echo "... cargo-clean_quiche-client"
	@echo "... NightlyTest"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyMemoryCheck"
	@echo "... ExperimentalTest"
	@echo "... ContinuousUpdate"
	@echo "... NightlyUpdate"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalSubmit"
	@echo "... Experimental"
	@echo "... ContinuousCoverage"
	@echo "... ExperimentalConfigure"
	@echo "... Continuous"
	@echo "... Nightly"
	@echo "... NightlySubmit"
	@echo "... NightlyStart"
	@echo "... ExperimentalCoverage"
	@echo "... NightlyCoverage"
	@echo "... ExperimentalStart"
	@echo "... NightlyBuild"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalUpdate"
	@echo "... ContinuousStart"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousTest"
	@echo "... ContinuousSubmit"
	@echo "... NightlyMemCheck"
	@echo "... examples/client.o"
	@echo "... examples/client.i"
	@echo "... examples/client.s"
	@echo "... examples/server.o"
	@echo "... examples/server.i"
	@echo "... examples/server.s"
	@echo "... lib/dtp_assemb.o"
	@echo "... lib/dtp_assemb.i"
	@echo "... lib/dtp_assemb.s"
	@echo "... lib/dtp_scheduler.o"
	@echo "... lib/dtp_scheduler.i"
	@echo "... lib/dtp_scheduler.s"
	@echo "... lib/dtp_tc.o"
	@echo "... lib/dtp_tc.i"
	@echo "... lib/dtp_tc.s"
	@echo "... lib/dtplayer.o"
	@echo "... lib/dtplayer.i"
	@echo "... lib/dtplayer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/lyx/projects/dss/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

